# Generated by Django 5.2.8 on 2025-11-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = []
