name: Bug report
about: Create a bug report
title: "bug: "
labels: ["type:bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
